version: "2"
services:
  dfanalyzer:
    image: dfanalyzer
    restart: always
    networks: 
      - network 
    environment:
      - DFA_URL=http://0.0.0.0
    ports:
      - 22000:22000
    working_dir: "/dataflow_analyzer/DfAnalyzer"
    entrypoint: ["sh", "start-dfanalyzer.sh"]

  server:
    image: dfanalyzer
    restart: always
    networks: 
      - network 
    environment:
      - DFA_URL=http://dfanalyzer:22000
    volumes: 
      - ./flowering:/dataflow_analyzer/applications/flowering
    working_dir: "/dataflow_analyzer/applications/flowering/"
    entrypoint: ["bash", "script/start_flower_server.sh", "config/flower_server.cfg"]

  client:
    image: dfanalyzer
    restart: always
    networks: 
      - network 
    environment:
      - DFA_URL=http://dfanalyzer:22000
    volumes: 
      - ./flowering:/dataflow_analyzer/applications/flowering
    working_dir: "/dataflow_analyzer/applications/flowering/"
    entrypoint: ["bash", "script/start_flower_client.sh", "1", "config/flower_client.cfg"]

      
networks:
  network:
    external: 
      name: flower-network

