version: "3.8"
services:
  dfanalyzer:
    image: dfanalyzer
    container_name: dfanalyzer
    restart: "no"
    network_mode: "host"
    environment:
      - DFA_URL=http://0.0.0.0
    # ports:
    #   - 22000:22000
    #   - 50000:50000
    volumes:
      - ./dataset-splitter/dataset_partitions:/dataset_partitions
    working_dir: "/DfAnalyzer"
    entrypoint: [ "sh", "start-dfanalyzer.sh" ]
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:22000"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s


  server:
    image: dfanalyzer
    container_name: server
    restart: "no"
    network_mode: "host"
    environment:
      - DFA_URL=http://localhost:22000
    # ports: 
    #  - 8080:8080
    volumes:
      - ./flowering:/applications/flowering
    working_dir: "/applications/flowering/"
    command: bash -c "python3 dfanalyzer-code/prospective_provenance.py && bash script/start_flower_server.sh config/flower_server.cfg"
    depends_on:
      dfanalyzer:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl","--http0.9", "http://localhost:8080"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s

  mongodb:
    image : mongo
    container_name: mongodb
    restart: "no"
    environment:
      # - PUID=1000
      # - PGID=1000
      - MONGO_INITDB_USERNAME=camila.lopes
      - MONGO_INITDB_PASSWORD=teste123
    # volumes:
    #   - ./data-mongo:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh --quiet | grep 1
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s

  client1:
    image: dfanalyzer
    restart: "no"
    network_mode: "host"
    environment:
      - DFA_URL=http://localhost:22000
    volumes:
      - ./flowering:/applications/flowering
      - ./dataset-splitter/dataset_partitions/partition_0:/dataset
    working_dir: "/applications/flowering/"
    entrypoint:
      [
        "bash",
        "script/start_flower_clients.sh",
        "0",
        "config/flower_clients.cfg"
      ]
    depends_on:
      server: 
        condition: service_healthy

  client2:
    image: dfanalyzer
    restart: "no"
    network_mode: "host"
    environment:
      - DFA_URL=http://localhost:22000
    volumes:
      - ./flowering:/applications/flowering
      - ./dataset-splitter/dataset_partitions/partition_1:/dataset
    working_dir: "/applications/flowering/"
    entrypoint:
      [
        "bash",
        "script/start_flower_clients.sh",
        "1",
        "config/flower_clients.cfg"
      ]
    depends_on:
      server: 
        condition: service_healthy

  client3:
    image: dfanalyzer
    restart: "no"
    network_mode: "host"
    environment:
      - DFA_URL=http://localhost:22000
    volumes:
      - ./flowering:/applications/flowering
      - ./dataset-splitter/dataset_partitions/partition_2:/dataset
    working_dir: "/applications/flowering/"
    entrypoint:
      [
        "bash",
        "script/start_flower_clients.sh",
        "2",
        "config/flower_clients.cfg"
      ]
    depends_on:
      server: 
        condition: service_healthy

  client4:
    image: dfanalyzer
    restart: "no"
    network_mode: "host"
    environment:
      - DFA_URL=http://localhost:22000
    volumes:
      - ./flowering:/applications/flowering
      - ./dataset-splitter/dataset_partitions/partition_3:/dataset
    working_dir: "/applications/flowering/"
    entrypoint:
      [
        "bash",
        "script/start_flower_clients.sh",
        "3",
        "config/flower_clients.cfg"
      ]
    depends_on:
      server: 
        condition: service_healthy

  client5:
    image: dfanalyzer
    restart: "no"
    network_mode: "host"
    environment:
      - DFA_URL=http://localhost:22000
    volumes:
      - ./flowering:/applications/flowering
      - ./dataset-splitter/dataset_partitions/partition_4:/dataset
    working_dir: "/applications/flowering/"
    entrypoint:
      [
        "bash",
        "script/start_flower_clients.sh",
        "4",
        "config/flower_clients.cfg"
      ]
    depends_on:
      server: 
        condition: service_healthy